
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=default
    depends_on:
      - redis

  redis:
    image: redis:6.2-alpine
    container_name: redis
    ports:
      - "6379:6379"

  h2-console:
    image: oscarfonts/h2
    container_name: h2-console
    ports:
      - "8081:8082"